### ISSUE TITLE
Container version not starting

### ISSUE THREAD

**Issue by 2fst4u** [librespeed/speedtest-go#16]
## Description
Unable to run the docker container

## Server
Raspberry pi 3B running K3S

## Client
Chrome on Android (works fine using the regular librespeed version)

## Steps to reproduce
Following the regular librespeed docker instructions I have a working install, however it's slow because of the PHP. In switching over to this version I have just changed the image line in my kubernetes deployment yaml file to pull this version, however the container doesn't pull and start.

## Expected behaviour
Container should pull and run.

This is my deployment yaml:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librespeed-deployment
  labels:
    app: librespeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librespeed
  template:
    metadata:
      labels:
        app: librespeed
    spec:
      containers:
      - name: librespeed
        image: mickkael/librespeed-go
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: 800Mi
            cpu: 2000m
          limits:
            memory: 800Mi
            cpu: 2000m
      priorityClassName: high-priority
---
kind: Service
apiVersion: v1
metadata:
  name: librespeed-service
spec:
  type: NodePort
  selector:
    app: librespeed
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30009
```

And this is the output I get when checking events:

`10m         Normal    Scheduled           pod/librespeed-deployment-768fd648b9-mt65r    Successfully assigned prod/librespeed-deployment-768fd648b9-mt65r to k3s-node1
9m53s       Normal    Pulled              pod/librespeed-deployment-768fd648b9-mt65r    Successfully pulled image "mickkael/librespeed-go"
9m52s       Normal    Created             pod/librespeed-deployment-768fd648b9-mt65r    Created container librespeed
9m52s       Normal    Started             pod/librespeed-deployment-768fd648b9-mt65r    Started container librespeed
9m3s        Normal    Pulling             pod/librespeed-deployment-768fd648b9-mt65r    Pulling image "mickkael/librespeed-go"
34s         Warning   BackOff             pod/librespeed-deployment-768fd648b9-mt65r    Back-off restarting failed container
`

Any ideas what I might be doing wrong?
